import type {
  CategoryStat,
  DashboardSidebarSection,
  KpiMetric,
  NotificationItem,
  OrderItem,
  ProductItem,
  RevenuePoint,
  SellerItem,
  TransactionItem,
  UserItem,
} from '../types/dashboard.types';

export const DASHBOARD_KPI_METRICS: KpiMetric[] = [
  {
    id: 'revenue',
    title: 'Total Revenue',
    value: '₾142,850',
    change: '+18.2%',
    changeType: 'up',
    icon: 'dollar-sign',
    color: 'text-green-500',
  },
  {
    id: 'orders',
    title: 'Total Orders',
    value: '3,284',
    change: '+12.5%',
    changeType: 'up',
    icon: 'shopping-cart',
    color: 'text-blue-500',
  },
  {
    id: 'users',
    title: 'Total Users',
    value: '12,489',
    change: '+9.1%',
    changeType: 'up',
    icon: 'users',
    color: 'text-purple-500',
  },
  {
    id: 'products',
    title: 'Total Products',
    value: '4,721',
    change: '+5.3%',
    changeType: 'up',
    icon: 'package',
    color: 'text-orange-500',
  },
  {
    id: 'sellers',
    title: 'Total Sellers',
    value: '842',
    change: '+3.7%',
    changeType: 'up',
    icon: 'store',
    color: 'text-pink-500',
  },
  {
    id: 'commission',
    title: 'Commission',
    value: '₾14,285',
    change: '+18.2%',
    changeType: 'up',
    icon: 'trending-up',
    color: 'text-primary',
  },
  {
    id: 'growth',
    title: 'Monthly Growth',
    value: '18.2%',
    change: '+2.4%',
    changeType: 'up',
    icon: 'bar-chart-2',
    color: 'text-teal-500',
  },
  {
    id: 'active',
    title: 'Active Listings',
    value: '3,912',
    change: '-1.2%',
    changeType: 'down',
    icon: 'list',
    color: 'text-red-500',
  },
];

export const REVENUE_DATA_7D: RevenuePoint[] = [
  { label: 'ორს', revenue: 7200, orders: 144, commission: 720 },
  { label: 'სამ', revenue: 8100, orders: 162, commission: 810 },
  { label: 'ოთხ', revenue: 6800, orders: 136, commission: 680 },
  { label: 'ხუთ', revenue: 9400, orders: 188, commission: 940 },
  { label: 'პარ', revenue: 11200, orders: 224, commission: 1120 },
  { label: 'შაბ', revenue: 13400, orders: 268, commission: 1340 },
  { label: 'კვი', revenue: 8900, orders: 178, commission: 890 },
];

export const REVENUE_DATA_30D: RevenuePoint[] = [
  { label: '1 მაი', revenue: 4200, orders: 84, commission: 420 },
  { label: '5 მაი', revenue: 5100, orders: 102, commission: 510 },
  { label: '10 მაი', revenue: 3800, orders: 76, commission: 380 },
  { label: '15 მაი', revenue: 6200, orders: 124, commission: 620 },
  { label: '20 მაი', revenue: 5800, orders: 116, commission: 580 },
  { label: '25 მაი', revenue: 7100, orders: 142, commission: 710 },
  { label: '30 მაი', revenue: 8400, orders: 168, commission: 840 },
  { label: '1 ივნ', revenue: 6900, orders: 138, commission: 690 },
  { label: '5 ივნ', revenue: 9200, orders: 184, commission: 920 },
  { label: '10 ივნ', revenue: 8100, orders: 162, commission: 810 },
  { label: '14 ივნ', revenue: 11200, orders: 224, commission: 1120 },
];

export const REVENUE_DATA_1Y: RevenuePoint[] = [
  { label: 'იან', revenue: 45000, orders: 900, commission: 4500 },
  { label: 'თებ', revenue: 38000, orders: 760, commission: 3800 },
  { label: 'მარ', revenue: 52000, orders: 1040, commission: 5200 },
  { label: 'აპრ', revenue: 61000, orders: 1220, commission: 6100 },
  { label: 'მაი', revenue: 58000, orders: 1160, commission: 5800 },
  { label: 'ივნ', revenue: 72000, orders: 1440, commission: 7200 },
  { label: 'ივლ', revenue: 85000, orders: 1700, commission: 8500 },
  { label: 'აგვ', revenue: 79000, orders: 1580, commission: 7900 },
  { label: 'სექ', revenue: 91000, orders: 1820, commission: 9100 },
  { label: 'ოქტ', revenue: 103000, orders: 2060, commission: 10300 },
  { label: 'ნოე', revenue: 118000, orders: 2360, commission: 11800 },
  { label: 'დეკ', revenue: 142850, orders: 2860, commission: 14285 },
];

export const RECENT_ORDERS: OrderItem[] = [
  {
    id: '1',
    orderNumber: 'ORD-2024-0891',
    customer: 'გიორგი ბერიძე',
    email: 'g.beridze@gmail.com',
    product: 'iPhone 15 Pro Max',
    amount: 2899,
    status: 'completed',
    date: '2024-06-14',
    category: 'მობილურები',
  },
  {
    id: '2',
    orderNumber: 'ORD-2024-0890',
    customer: 'ნინო ქართველიშვილი',
    email: 'nino.k@gmail.com',
    product: 'Samsung 4K TV 55"',
    amount: 1450,
    status: 'pending',
    date: '2024-06-14',
    category: 'ტელევიზორები',
  },
  {
    id: '3',
    orderNumber: 'ORD-2024-0889',
    customer: 'ლუკა მამულაძე',
    email: 'luka.m@outlook.com',
    product: 'MacBook Air M2',
    amount: 3200,
    status: 'processing',
    date: '2024-06-13',
    category: 'კომპიუტერები',
  },
  {
    id: '4',
    orderNumber: 'ORD-2024-0888',
    customer: 'მარი ჯანაშია',
    email: 'mari.j@gmail.com',
    product: 'Sony WH-1000XM5',
    amount: 480,
    status: 'completed',
    date: '2024-06-13',
    category: 'ფოტო / ვიდეო',
  },
  {
    id: '5',
    orderNumber: 'ORD-2024-0887',
    customer: 'ბექა ლომიძე',
    email: 'beka.l@gmail.com',
    product: 'PlayStation 5',
    amount: 1100,
    status: 'cancelled',
    date: '2024-06-12',
    category: 'გართობა',
  },
  {
    id: '6',
    orderNumber: 'ORD-2024-0886',
    customer: 'თამარ კვარაცხელია',
    email: 'tamar.k@gmail.com',
    product: 'LG Monitor 27"',
    amount: 520,
    status: 'completed',
    date: '2024-06-12',
    category: 'კომპიუტერები',
  },
  {
    id: '7',
    orderNumber: 'ORD-2024-0885',
    customer: 'სანდრო ჭანტურია',
    email: 'sandro.ch@gmail.com',
    product: 'DJI Mini 4 Pro',
    amount: 1650,
    status: 'processing',
    date: '2024-06-11',
    category: 'ფოტო / ვიდეო',
  },
  {
    id: '8',
    orderNumber: 'ORD-2024-0884',
    customer: 'ანა მელიქიშვილი',
    email: 'ana.m@gmail.com',
    product: 'Dyson V15 Detect',
    amount: 780,
    status: 'refunded',
    date: '2024-06-11',
    category: 'სახლი',
  },
];

export const ALL_ORDERS: OrderItem[] = [
  ...RECENT_ORDERS,
  {
    id: '9',
    orderNumber: 'ORD-2024-0883',
    customer: 'ზაქარია გოგუა',
    email: 'z.gogua@gmail.com',
    product: 'Samsung Galaxy S24 Ultra',
    amount: 2400,
    status: 'completed',
    date: '2024-06-10',
    category: 'მობილურები',
  },
  {
    id: '10',
    orderNumber: 'ORD-2024-0882',
    customer: 'ნათია შენგელია',
    email: 'n.shengelia@gmail.com',
    product: 'Apple Watch Series 9',
    amount: 620,
    status: 'completed',
    date: '2024-06-10',
    category: 'სმარტ-საათები',
  },
  {
    id: '11',
    orderNumber: 'ORD-2024-0881',
    customer: 'დავით ჩხეიძე',
    email: 'd.chkheidze@gmail.com',
    product: 'ASUS ROG Gaming Laptop',
    amount: 3800,
    status: 'pending',
    date: '2024-06-09',
    category: 'კომპიუტერები',
  },
  {
    id: '12',
    orderNumber: 'ORD-2024-0880',
    customer: 'ეკა ტაბატაძე',
    email: 'e.tabatadze@gmail.com',
    product: 'Kindle Paperwhite',
    amount: 180,
    status: 'completed',
    date: '2024-06-09',
    category: 'წიგნები',
  },
];

export const TOP_PRODUCTS: ProductItem[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    category: 'მობილურები',
    price: 2899,
    stock: 45,
    sales: 284,
    revenue: 82524,
    status: 'active',
    seller: 'TechStore GE',
    rating: 4.9,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'MacBook Air M2',
    category: 'კომპიუტერები',
    price: 3200,
    stock: 12,
    sales: 156,
    revenue: 49920,
    status: 'active',
    seller: 'Apple Premium GE',
    rating: 4.8,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Samsung 4K TV 55"',
    category: 'ტელევიზორები',
    price: 1450,
    stock: 28,
    sales: 203,
    revenue: 29435,
    status: 'active',
    seller: 'Samsung GE',
    rating: 4.7,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5',
    category: 'ფოტო / ვიდეო',
    price: 480,
    stock: 67,
    sales: 412,
    revenue: 19776,
    status: 'active',
    seller: 'SoundPro GE',
    rating: 4.9,
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    name: 'PlayStation 5',
    category: 'გართობა',
    price: 1100,
    stock: 8,
    sales: 178,
    revenue: 19580,
    status: 'out_of_stock',
    seller: 'GameZone GE',
    rating: 4.8,
    createdAt: '2024-01-01',
  },
  {
    id: '6',
    name: 'DJI Mini 4 Pro',
    category: 'ფოტო / ვიდეო',
    price: 1650,
    stock: 22,
    sales: 92,
    revenue: 15180,
    status: 'active',
    seller: 'DroneTech GE',
    rating: 4.7,
    createdAt: '2024-02-28',
  },
  {
    id: '7',
    name: 'iPad Air M2',
    category: 'მობილურები',
    price: 1850,
    stock: 34,
    sales: 134,
    revenue: 12390,
    status: 'active',
    seller: 'Apple Premium GE',
    rating: 4.8,
    createdAt: '2024-03-15',
  },
  {
    id: '8',
    name: 'LG OLED Monitor 27"',
    category: 'კომპიუტერები',
    price: 890,
    stock: 0,
    sales: 67,
    revenue: 8963,
    status: 'out_of_stock',
    seller: 'LG Premium GE',
    rating: 4.6,
    createdAt: '2024-04-01',
  },
  {
    id: '9',
    name: 'Bose SoundLink Max',
    category: 'ფოტო / ვიდეო',
    price: 340,
    stock: 89,
    sales: 245,
    revenue: 7905,
    status: 'active',
    seller: 'SoundPro GE',
    rating: 4.7,
    createdAt: '2024-04-10',
  },
  {
    id: '10',
    name: 'Xiaomi Robot Vacuum',
    category: 'სახლი',
    price: 520,
    stock: 15,
    sales: 112,
    revenue: 5824,
    status: 'pending',
    seller: 'SmartHome GE',
    rating: 4.5,
    createdAt: '2024-05-01',
  },
];

export const USERS_LIST: UserItem[] = [
  {
    id: '1',
    name: 'გიორგი ბერიძე',
    email: 'g.beridze@gmail.com',
    role: 'user',
    status: 'active',
    joinDate: '2024-01-10',
    orders: 12,
    totalSpent: 4580,
  },
  {
    id: '2',
    name: 'ნინო ქართველიშვილი',
    email: 'nino.k@gmail.com',
    role: 'user',
    status: 'active',
    joinDate: '2024-01-15',
    orders: 8,
    totalSpent: 2340,
  },
  {
    id: '3',
    name: 'ლუკა მამულაძე',
    email: 'luka.m@outlook.com',
    role: 'seller',
    status: 'active',
    joinDate: '2024-02-01',
    orders: 3,
    totalSpent: 980,
  },
  {
    id: '4',
    name: 'მარი ჯანაშია',
    email: 'mari.j@gmail.com',
    role: 'user',
    status: 'active',
    joinDate: '2024-02-15',
    orders: 6,
    totalSpent: 1890,
  },
  {
    id: '5',
    name: 'ბექა ლომიძე',
    email: 'beka.l@gmail.com',
    role: 'user',
    status: 'inactive',
    joinDate: '2024-03-01',
    orders: 2,
    totalSpent: 340,
  },
  {
    id: '6',
    name: 'თამარ კვარაცხელია',
    email: 'tamar.k@gmail.com',
    role: 'seller',
    status: 'active',
    joinDate: '2024-03-10',
    orders: 15,
    totalSpent: 5670,
  },
  {
    id: '7',
    name: 'სანდრო ჭანტურია',
    email: 'sandro.ch@gmail.com',
    role: 'user',
    status: 'banned',
    joinDate: '2024-03-20',
    orders: 0,
    totalSpent: 0,
  },
  {
    id: '8',
    name: 'ანა მელიქიშვილი',
    email: 'ana.m@gmail.com',
    role: 'user',
    status: 'active',
    joinDate: '2024-04-01',
    orders: 4,
    totalSpent: 1240,
  },
  {
    id: '9',
    name: 'ზაქარია გოგუა',
    email: 'z.gogua@gmail.com',
    role: 'admin',
    status: 'active',
    joinDate: '2023-06-01',
    orders: 0,
    totalSpent: 0,
  },
  {
    id: '10',
    name: 'ნათია შენგელია',
    email: 'n.shengelia@gmail.com',
    role: 'seller',
    status: 'active',
    joinDate: '2023-10-20',
    orders: 5,
    totalSpent: 1890,
  },
];

export const SELLERS_LIST: SellerItem[] = [
  {
    id: '1',
    name: 'ვახო ბაქრაძე',
    email: 'v.bakradze@techstore.ge',
    storeName: 'TechStore GE',
    revenue: 82524,
    products: 145,
    rating: 4.9,
    totalSales: 1284,
    status: 'active',
    joinDate: '2023-06-01',
    commissionRate: 8,
  },
  {
    id: '2',
    name: 'სალომე ქობულია',
    email: 's.kobuliya@apple-premium.ge',
    storeName: 'Apple Premium GE',
    revenue: 62310,
    products: 87,
    rating: 4.8,
    totalSales: 890,
    status: 'active',
    joinDate: '2023-08-15',
    commissionRate: 8,
  },
  {
    id: '3',
    name: 'ზაქარია გოგუა',
    email: 'z.gogua@samsung.ge',
    storeName: 'Samsung GE',
    revenue: 45670,
    products: 234,
    rating: 4.7,
    totalSales: 2103,
    status: 'active',
    joinDate: '2023-09-01',
    commissionRate: 7,
  },
  {
    id: '4',
    name: 'ნათია შენგელია',
    email: 'n.shengelia@soundpro.ge',
    storeName: 'SoundPro GE',
    revenue: 28450,
    products: 62,
    rating: 4.9,
    totalSales: 912,
    status: 'active',
    joinDate: '2023-10-20',
    commissionRate: 9,
  },
  {
    id: '5',
    name: 'დავით ჩხეიძე',
    email: 'd.chkheidze@gamezone.ge',
    storeName: 'GameZone GE',
    revenue: 21890,
    products: 98,
    rating: 4.8,
    totalSales: 678,
    status: 'active',
    joinDate: '2024-01-05',
    commissionRate: 8,
  },
  {
    id: '6',
    name: 'ეკა ტაბატაძე',
    email: 'e.tabatadze@dronetech.ge',
    storeName: 'DroneTech GE',
    revenue: 15180,
    products: 23,
    rating: 4.7,
    totalSales: 92,
    status: 'pending',
    joinDate: '2024-03-10',
    commissionRate: 10,
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: '1',
    type: 'order',
    title: 'ახალი შეკვეთა',
    message: 'გ. ბერიძემ შეუკვეთა iPhone 15 Pro Max — ₾2,899',
    time: '5 წუთის წინ',
    read: false,
  },
  {
    id: '2',
    type: 'user',
    title: 'ახალი მომხმარებელი',
    message: 'ნინო ქართველიშვილი დარეგისტრირდა',
    time: '12 წუთის წინ',
    read: false,
  },
  {
    id: '3',
    type: 'seller',
    title: 'გამყიდველის მოთხოვნა',
    message: 'DroneTech GE ელოდება დადასტურებას',
    time: '1 საათის წინ',
    read: false,
  },
  {
    id: '4',
    type: 'payment',
    title: 'გადახდა განხორციელდა',
    message: 'TechStore GE-ს ჩაეთვალა ₾8,252',
    time: '2 საათის წინ',
    read: true,
  },
  {
    id: '5',
    type: 'product',
    title: 'პროდუქტი დასამტკიცებლად',
    message: '3 ახალი პროდუქტი ელოდება მოდერაციას',
    time: '3 საათის წინ',
    read: true,
  },
  {
    id: '6',
    type: 'system',
    title: 'სისტემის შეტყობინება',
    message: 'ბაზა წარმატებით სინქრონიზდა',
    time: '5 საათის წინ',
    read: true,
  },
];

export const TRANSACTIONS: TransactionItem[] = [
  {
    id: '1',
    type: 'order',
    amount: 2899,
    status: 'completed',
    from: 'გ. ბერიძე',
    to: 'TechStore GE',
    date: '2024-06-14',
    description: 'iPhone 15 Pro Max',
  },
  {
    id: '2',
    type: 'commission',
    amount: 290,
    status: 'completed',
    from: 'TechStore GE',
    to: 'Trendora',
    date: '2024-06-14',
    description: 'Commission 10%',
  },
  {
    id: '3',
    type: 'payout',
    amount: 8252,
    status: 'completed',
    from: 'Trendora',
    to: 'TechStore GE',
    date: '2024-06-13',
    description: 'ყოველკვირეული ანგარიშსწორება',
  },
  {
    id: '4',
    type: 'refund',
    amount: 780,
    status: 'completed',
    from: 'Trendora',
    to: 'ა. მელიქიშვილი',
    date: '2024-06-11',
    description: 'Dyson V15 — დაბრუნება',
  },
  {
    id: '5',
    type: 'order',
    amount: 3200,
    status: 'pending',
    from: 'ლ. მამულაძე',
    to: 'Apple Premium GE',
    date: '2024-06-13',
    description: 'MacBook Air M2',
  },
  {
    id: '6',
    type: 'payout',
    amount: 6230,
    status: 'completed',
    from: 'Trendora',
    to: 'Apple Premium GE',
    date: '2024-06-12',
    description: 'ყოველკვირეული ანგარიშსწორება',
  },
  {
    id: '7',
    type: 'commission',
    amount: 1100,
    status: 'pending',
    from: 'Samsung GE',
    to: 'Trendora',
    date: '2024-06-12',
    description: 'Commission 7%',
  },
];

export const CATEGORY_STATS: CategoryStat[] = [
  { name: 'მობილურები', products: 892, revenue: 145000, growth: '+24%' },
  { name: 'კომპიუტერები', products: 634, revenue: 98000, growth: '+18%' },
  { name: 'ტელევიზორები', products: 345, revenue: 67000, growth: '+12%' },
  { name: 'ფოტო / ვიდეო', products: 421, revenue: 54000, growth: '+31%' },
  { name: 'გართობა', products: 289, revenue: 43000, growth: '+8%' },
  { name: 'სახლი', products: 567, revenue: 38000, growth: '+15%' },
];

export const DASHBOARD_NAV_SECTIONS: DashboardSidebarSection[] = [
  {
    title: 'მთავარი',
    items: [
      { href: '/dashboard', label: 'მიმოხილვა', icon: 'layout-dashboard' },
      { href: '/dashboard/analytics', label: 'ანალიტიკა', icon: 'bar-chart-2' },
      { href: '/dashboard/reports', label: 'ანგარიშები', icon: 'file-text' },
    ],
  },
  {
    title: 'მართვა',
    items: [
      { href: '/dashboard/orders', label: 'შეკვეთები', icon: 'shopping-cart', badge: 12 },
      { href: '/dashboard/products', label: 'პროდუქტები', icon: 'package' },
      { href: '/dashboard/categories', label: 'კატეგორიები', icon: 'tag' },
      { href: '/dashboard/sellers', label: 'გამყიდველები', icon: 'store', badge: 2 },
      { href: '/dashboard/users', label: 'მომხმარებლები', icon: 'users' },
    ],
  },
  {
    title: 'ფინანსები',
    items: [
      { href: '/dashboard/financial', label: 'ფინანსები', icon: 'dollar-sign' },
    ],
  },
  {
    title: 'AI',
    items: [
      { href: '/dashboard/ai', label: 'AI ასისტენტი', icon: 'bot' },
    ],
  },
  {
    title: 'სისტემა',
    items: [
      { href: '/dashboard/notifications', label: 'შეტყობინებები', icon: 'bell', badge: 3 },
      { href: '/dashboard/settings', label: 'პარამეტრები', icon: 'settings' },
    ],
  },
];

export const DASHBOARD_PAGE_TITLES: Record<string, string> = {
  '/dashboard': 'მიმოხილვა',
  '/dashboard/analytics': 'ანალიტიკა',
  '/dashboard/reports': 'ანგარიშები',
  '/dashboard/orders': 'შეკვეთები',
  '/dashboard/products': 'პროდუქტები',
  '/dashboard/categories': 'კატეგორიები',
  '/dashboard/sellers': 'გამყიდველები',
  '/dashboard/users': 'მომხმარებლები',
  '/dashboard/financial': 'ფინანსები',
  '/dashboard/ai': 'AI ასისტენტი',
  '/dashboard/notifications': 'შეტყობინებები',
  '/dashboard/settings': 'პარამეტრები',
};
